id: 57840b4d2cc5c46981d5b9e07c9b7b06d5bcf064
bug_link: https://syzkaller.appspot.com/bug?extid=57840b4d2cc5c46981d5b9e07c9b7b06d5bcf064
title: 'kernel panic: n_tty: init_tty'
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: 598c2d41ff44889dd8eced4f117403e472158d85
fix_commit: 903f9db10f18f735e62ba447147b6c434b6af003
datetime: '2018-04-23T11:05:52+02:00'
fix_commit_message: 'tty: Don''t call panic() at tty_ldisc_init()


  syzbot is reporting kernel panic [1] triggered by memory allocation failure

  at tty_ldisc_get() from tty_ldisc_init(). But since both tty_ldisc_get()

  and caller of tty_ldisc_init() can cleanly handle errors, tty_ldisc_init()

  does not need to call panic() when tty_ldisc_get() failed.


  [1] https://syzkaller.appspot.com/bug?id=883431818e036ae6a9981156a64b821110f39187


  Signed-off-by: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>

  Reported-by: syzbot <syzkaller@googlegroups.com>

  Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

  Cc: Jiri Slaby <jslaby@suse.com>

  Cc: stable <stable@vger.kernel.org>

  Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

  '
submodule:
- drivers/tty
- include/linux
hunk_count: 3
covered_count: 2
