id: ab0cfe96c2b3cd1c1153
bug_link: https://syzkaller.appspot.com/bug?extid=ab0cfe96c2b3cd1c1153
title: WARNING in io_try_cancel_userdata (2)
source_page: https://syzkaller.appspot.com/upstream/fixed
trigger_commit: 674ee8e1b4a41d2fdffc885c55350c3fbb38c22a
fix_commit: 617a89484debcd4e7999796d693cf0b77d2519de
datetime: '2021-11-26T08:35:43-07:00'
fix_commit_message: "io_uring: fail cancellation for EXITING tasks\n\nWARNING: CPU:\
  \ 1 PID: 20 at fs/io_uring.c:6269 io_try_cancel_userdata+0x3c5/0x640 fs/io_uring.c:6269\n\
  CPU: 1 PID: 20 Comm: kworker/1:0 Not tainted 5.16.0-rc1-syzkaller #0\nWorkqueue:\
  \ events io_fallback_req_func\nRIP: 0010:io_try_cancel_userdata+0x3c5/0x640 fs/io_uring.c:6269\n\
  Call Trace:\n <TASK>\n io_req_task_link_timeout+0x6b/0x1e0 fs/io_uring.c:6886\n\
  \ io_fallback_req_func+0xf9/0x1ae fs/io_uring.c:1334\n process_one_work+0x9b2/0x1690\
  \ kernel/workqueue.c:2298\n worker_thread+0x658/0x11f0 kernel/workqueue.c:2445\n\
  \ kthread+0x405/0x4f0 kernel/kthread.c:327\n ret_from_fork+0x1f/0x30 arch/x86/entry/entry_64.S:295\n\
  \ </TASK>\n\nWe need original task's context to do cancellations, so if it's dying\n\
  and the callback is executed in a fallback mode, fail the cancellation\nattempt.\n\
  \nFixes: 89b263f6d56e6 (\"io_uring: run linked timeouts from task_work\")\nCc: stable@kernel.org\
  \ # 5.15+\nReported-by: syzbot+ab0cfe96c2b3cd1c1153@syzkaller.appspotmail.com\n\
  Signed-off-by: Pavel Begunkov <asml.silence@gmail.com>\nLink: https://lore.kernel.org/r/4c41c5f379c6941ad5a07cd48cb66ed62199cf7e.1637937097.git.asml.silence@gmail.com\n\
  Signed-off-by: Jens Axboe <axboe@kernel.dk>\n"
submodule:
- fs
hunk_count: 1
covered_count: 1
